name: eztime
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: "https://github.com/jaq-the-cat/eztime"

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
